"use client";
import { useMemo,useState } from "react"; import Link from "next/link"; import { Search,SlidersHorizontal } from "lucide-react";
import { formatDate,formatMoney } from "@/lib/utils"; import { Input,Select } from "@/components/ui/input"; import { StatusBadge } from "@/components/ui/badge"; import { shipmentStatuses,type Shipment } from "@/types"; import { ShipmentRowActions } from "./shipment-row-actions";

export function ShipmentsTable({shipments,isDemo}:{shipments:Shipment[];isDemo:boolean}){
  const[q,setQ]=useState(""); const[status,setStatus]=useState("All");
  const rows=useMemo(()=>shipments.filter(s=>(status==="All"||s.status===status)&&`${s.referenceNumber} ${s.client} ${s.pickupCity} ${s.deliveryCity}`.toLowerCase().includes(q.toLowerCase())),[q,status,shipments]);
  return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
    {isDemo&&<div className="border-b border-amber-200 bg-amber-50 px-5 py-3 text-sm text-amber-800">Read-only demo data. Live workspaces load shipments from Supabase.</div>}
    <div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><Input aria-label="Search shipments" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reference, client or route…" className="pl-9"/></div><div className="relative sm:w-48"><SlidersHorizontal className="pointer-events-none absolute left-3 top-3 text-slate-400" size={16}/><Select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)} className="pl-9"><option>All</option>{shipmentStatuses.map(s=><option key={s}>{s}</option>)}</Select></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Reference","Route","Client / Carrier","Dates","Revenue","Profit","Margin","Status",...(isDemo?[]:["Actions"])].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(s=><tr key={s.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><Link className="font-semibold text-emerald-800 hover:underline" href={`/shipments/${s.id}`}>{s.referenceNumber}</Link></td><td className="px-5 py-4 font-medium">{s.pickupCity} <span className="text-slate-400">→</span> {s.deliveryCity}</td><td className="px-5 py-4"><p>{s.client}</p><p className="mt-1 text-xs text-slate-500">{s.carrier}</p></td><td className="px-5 py-4"><p>{formatDate(s.pickupDate)}</p><p className="mt-1 text-xs text-slate-500">to {formatDate(s.deliveryDate)}</p></td><td className="px-5 py-4 font-medium">{formatMoney(s.clientPrice,s.currency)}</td><td className="px-5 py-4 font-semibold text-emerald-700">{formatMoney(s.profit,s.currency)}</td><td className="px-5 py-4">{s.marginPercent}%</td><td className="px-5 py-4"><StatusBadge status={s.status}/></td>{!isDemo&&<td className="px-5 py-4"><ShipmentRowActions id={s.id} status={s.status}/></td>}</tr>)}</tbody></table>{!rows.length&&<div className="p-12 text-center text-sm text-slate-500">{shipments.length?"No shipments match your filters.":"No shipments yet. Create your first freight order."}</div>}</div>
    <div className="flex items-center justify-between border-t border-slate-200 px-5 py-4 text-sm text-slate-500"><span>Showing {rows.length} of {shipments.length} shipments</span><span>{isDemo?"Demo dataset":"Live workspace"}</span></div>
  </div>;
}
