"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { carrierFormSchema, clientFormSchema } from "@/lib/validation/directory";
import { shipmentFormSchema } from "@/lib/validation/shipment";

export type ActionResult = { ok:true } | { ok:false; message:string; fieldErrors?:Record<string,string[]> };
const idSchema=z.string().uuid();

async function auth(){const supabase=await createClient();if(!supabase)return null;const{data:{user}}=await supabase.auth.getUser();return user?{supabase,user}:null}
function refreshShipments(){revalidatePath("/shipments");revalidatePath("/dashboard");revalidatePath("/analytics")}
function refreshDirectory(type:"clients"|"carriers"){revalidatePath(`/${type}`);revalidatePath("/shipments");revalidatePath("/dashboard");revalidatePath("/analytics")}

export async function upsertShipment(formData:FormData,shipmentId?:string):Promise<ActionResult>{const parsed=shipmentFormSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{ok:false,message:"Check the highlighted fields.",fieldErrors:parsed.error.flatten().fieldErrors};const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const payload={...parsed.data,notes:parsed.data.notes||null};const query=shipmentId?session.supabase.from("shipments").update(payload).eq("id",idSchema.parse(shipmentId)):session.supabase.from("shipments").insert({...payload,user_id:session.user.id});const{error}=await query;if(error)return{ok:false,message:error.code==="23505"?"This reference number already exists.":"The shipment could not be saved."};refreshShipments();return{ok:true}}
export async function deleteShipment(shipmentId:string):Promise<ActionResult>{const parsed=idSchema.safeParse(shipmentId);if(!parsed.success)return{ok:false,message:"Invalid shipment."};const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const{error}=await session.supabase.from("shipments").delete().eq("id",parsed.data);if(error)return{ok:false,message:"The shipment could not be deleted."};refreshShipments();return{ok:true}}
export async function updateShipmentStatus(shipmentId:string,status:string):Promise<ActionResult>{const parsed=z.object({id:idSchema,status:z.enum(["New","Accepted","In Transit","Delivered","Cancelled","Issue"])}).safeParse({id:shipmentId,status});if(!parsed.success)return{ok:false,message:"Invalid status."};const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const{error}=await session.supabase.from("shipments").update({status:parsed.data.status}).eq("id",parsed.data.id);if(error)return{ok:false,message:"The status could not be updated."};refreshShipments();return{ok:true}}

export async function createStarterDirectory():Promise<ActionResult>{const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const[{data:clients},{data:carriers}]=await Promise.all([session.supabase.from("clients").select("id").limit(1),session.supabase.from("carriers").select("id").limit(1)]);if(!clients?.length){const{error}=await session.supabase.from("clients").insert({user_id:session.user.id,company_name:"Starter Client",tax_id:"PL0000000000",contact_person:"Demo Contact",email:"client@example.com",phone:"+48000000000"});if(error)return{ok:false,message:"Could not create the starter client."}}if(!carriers?.length){const{error}=await session.supabase.from("carriers").insert({user_id:session.user.id,company_name:"Starter Carrier",country:"Poland",contact_person:"Demo Dispatcher",email:"carrier@example.com",phone:"+48000000001",vehicle_type:"Curtainsider",rating:5});if(error)return{ok:false,message:"Could not create the starter carrier."}}revalidatePath("/shipments/new");refreshDirectory("clients");refreshDirectory("carriers");return{ok:true}}

export async function upsertClient(formData:FormData,clientId?:string):Promise<ActionResult>{const parsed=clientFormSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{ok:false,message:"Check the highlighted fields.",fieldErrors:parsed.error.flatten().fieldErrors};const id=clientId?idSchema.safeParse(clientId):null;if(id&&!id.success)return{ok:false,message:"Invalid client."};const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const query=id?session.supabase.from("clients").update(parsed.data).eq("id",id.data):session.supabase.from("clients").insert({...parsed.data,user_id:session.user.id});const{error}=await query;if(error)return{ok:false,message:"The client could not be saved."};refreshDirectory("clients");return{ok:true}}
export async function deleteClient(clientId:string):Promise<ActionResult>{const id=idSchema.safeParse(clientId);if(!id.success)return{ok:false,message:"Invalid client."};const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const{error}=await session.supabase.from("clients").delete().eq("id",id.data);if(error?.code==="23503")return{ok:false,message:"Reassign or delete this client's shipments first."};if(error)return{ok:false,message:"The client could not be deleted."};refreshDirectory("clients");return{ok:true}}
export async function upsertCarrier(formData:FormData,carrierId?:string):Promise<ActionResult>{const parsed=carrierFormSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{ok:false,message:"Check the highlighted fields.",fieldErrors:parsed.error.flatten().fieldErrors};const id=carrierId?idSchema.safeParse(carrierId):null;if(id&&!id.success)return{ok:false,message:"Invalid carrier."};const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const query=id?session.supabase.from("carriers").update(parsed.data).eq("id",id.data):session.supabase.from("carriers").insert({...parsed.data,user_id:session.user.id});const{error}=await query;if(error)return{ok:false,message:"The carrier could not be saved."};refreshDirectory("carriers");return{ok:true}}
export async function deleteCarrier(carrierId:string):Promise<ActionResult>{const id=idSchema.safeParse(carrierId);if(!id.success)return{ok:false,message:"Invalid carrier."};const session=await auth();if(!session)return{ok:false,message:"Your session expired. Sign in again."};const{error}=await session.supabase.from("carriers").delete().eq("id",id.data);if(error?.code==="23503")return{ok:false,message:"Reassign or delete this carrier's shipments first."};if(error)return{ok:false,message:"The carrier could not be deleted."};refreshDirectory("carriers");return{ok:true}}

export async function signOut(){const supabase=await createClient();await supabase?.auth.signOut();redirect("/login")}
